compressionLevel: 0
defaultSemverRangePrefix: ""
enableGlobalCache: false
enableMessageNames: false
nodeLinker: node-modules
plugins:
  - checksum: 351165af3f87af1ec24528ccf2affc93f57694cc7bfc51a1842d8c17e19d4c7275176de471df52f3b462b7fb16615a1961896c3823b68c330317035020e92e40
    path: .yarn/plugins/@yarnpkg/plugin-conventional-version.cjs
    spec: https://raw.githubusercontent.com/christophehurpeau/yarn-plugin-conventional-version/main/bundles/@yarnpkg/plugin-conventional-version.cjs
supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin
