defaultSemverRangePrefix: ""
enableMessageNames: false
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.6.1.cjs
supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin
