compressionLevel: 0
defaultSemverRangePrefix: ""
enableGlobalCache: false
enableMessageNames: false
nodeLinker: node-modules
plugins:
  - checksum: >-
      daf593fe9ebb6ca785ce3618be8b44ccbcfbfac33a23e18615915a04bb44672641902b645c79a6f58315e995048a7a6cc5956cc83712108dc8d25a5b3ccfaa30
    path: .yarn/plugins/@yarnpkg/plugin-conventional-version.cjs
    spec: >-
      https://raw.githubusercontent.com/christophehurpeau/yarn-plugin-conventional-version/main/bundles/%40yarnpkg/plugin-conventional-version.cjs
supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin
