/**
 * Regenerate the bot logos in packages/reviewflow/logos.
 *
 * Usage: pnpm --filter webapp run build:logos
 *
 * The mark is the phosphor `Checks` icon shipped by alouette-icons — the same
 * double checkmark the hand-drawn logos had — and its green is read straight
 * out of the palette [build-theme.ts](build-theme.ts) generates, so a hue
 * change there only has to be followed by a re-run here. The logos belong to
 * the bot, but the brand they are drawn from lives in this package, which is
 * also the only one already depending on alouette-icons and playwright.
 *
 * Two treatments, because the right one depends on where the file is uploaded:
 * `flat` is the bare green mark, for a surface whose background we control;
 * `disc` is the white mark on a filled brand disc, the same composition as
 * alouette's `BrandLogo` in the webapp header, for an avatar slot that crops to
 * a square and is rendered over both light and dark chrome (GitHub App, Slack).
 *
 * Rasterizing goes through playwright's chromium rather than a dedicated svg
 * renderer: it is already installed for the browser tests.
 */

/* eslint-disable no-console -- this is a cli script, its output is the point */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright";

const iconName = "ChecksRegularIcon";
const logosDir = new URL("../reviewflow/logos/", import.meta.url);
const paletteCssUrl = new URL("./src/palette.css", import.meta.url);

interface BrandColors {
  /** The brand green, as used for a filled surface. */
  green: string;
  /** What stays readable on top of that green. */
  onGreen: string;
}

/**
 * The palette is generated by alouette's theme generator, which writes every
 * accent as a `.<mode>_<accent>` block of custom properties.
 */
function readBrandColors(): BrandColors {
  const css = readFileSync(paletteCssUrl, "utf8");
  const block = /\.light_brand\s*\{([^}]*)\}/.exec(css)?.[1];
  if (!block) {
    throw new Error(
      `no .light_brand block in ${fileURLToPath(paletteCssUrl)}, did the theme generator change?`,
    );
  }

  const readVariable = (name: string): string => {
    const value = new RegExp(`--color-${name}:\\s*([^;]+);`).exec(block)?.[1];
    if (!value) {
      throw new Error(`no --color-${name} in the .light_brand palette block`);
    }
    return value.trim();
  };

  return { green: readVariable("enabled"), onGreen: readVariable("on-accent") };
}

interface IconSource {
  viewBox: string;
  paths: string[];
}

/**
 * alouette-icons ships each phosphor icon as a generated module wrapping plain
 * svg paths, so the geometry is read out of the source instead of rendering the
 * react component, which would drag react-dom into a script that draws no ui.
 */
function readIconSource(name: string): IconSource {
  const modulePath = fileURLToPath(
    import.meta.resolve(`alouette-icons/phosphor-icons/${name}`),
  );
  const source = readFileSync(modulePath, "utf8");
  const viewBox = /viewBox:\s*"([^"]+)"/.exec(source)?.[1];
  const paths = [...source.matchAll(/\bd:\s*"([^"]+)"/g)].flatMap(
    ([, pathData]) => pathData ?? [],
  );
  if (!viewBox || paths.length === 0) {
    throw new Error(`no svg path found in ${modulePath}`);
  }
  return { viewBox, paths };
}

type Treatment = "disc" | "flat";

interface BuildSvgParams {
  treatment: Treatment;
  /** Share of the canvas the icon box spans, centered. */
  iconRatio: number;
  /** Opaque fill painted edge to edge, or undefined to stay transparent. */
  background: string | undefined;
  size: number;
  icon: IconSource;
  colors: BrandColors;
}

function buildSvg({
  treatment,
  iconRatio,
  background,
  size,
  icon,
  colors,
}: BuildSvgParams): string {
  const [minX, minY, viewWidth, viewHeight] = icon.viewBox
    .split(/\s+/)
    .map(Number) as [number, number, number, number];
  const centerX = minX + viewWidth / 2;
  const centerY = minY + viewHeight / 2;

  const backgroundRect = background
    ? `<rect x="${minX}" y="${minY}" width="${viewWidth}" height="${viewHeight}" fill="${background}"/>`
    : "";
  const disc =
    treatment === "disc"
      ? `<circle cx="${centerX}" cy="${centerY}" r="${Math.min(viewWidth, viewHeight) / 2}" fill="${colors.green}"/>`
      : "";
  const iconFill = treatment === "disc" ? colors.onGreen : colors.green;
  const iconTransform = `translate(${centerX} ${centerY}) scale(${iconRatio}) translate(${-centerX} ${-centerY})`;

  return [
    `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="${icon.viewBox}">`,
    backgroundRect,
    disc,
    `<g transform="${iconTransform}" fill="${iconFill}">`,
    ...icon.paths.map((pathData) => `<path d="${pathData}"/>`),
    "</g>",
    "</svg>",
  ].join("");
}

interface LogoSpec extends Omit<BuildSvgParams, "colors" | "icon"> {
  fileName: string;
}

// Matching the mark the previous logos drew: it spanned all but a couple of
// pixels of the canvas.
const flatIconRatio = 0.96;
// The disc composition alouette's BrandLogo uses: a 22px icon on a 32px disc.
const discIconRatio = 22 / 32;

const logos: LogoSpec[] = [
  {
    fileName: "reviewflow.png",
    treatment: "flat",
    size: 96,
    background: undefined,
    iconRatio: flatIconRatio,
  },
  {
    fileName: "reviewflow_512.png",
    treatment: "flat",
    size: 512,
    background: undefined,
    iconRatio: flatIconRatio,
  },
  {
    fileName: "reviewflow_white.png",
    treatment: "flat",
    size: 96,
    background: "#ffffff",
    iconRatio: flatIconRatio,
  },
  {
    fileName: "reviewflow_white_512.png",
    treatment: "flat",
    size: 512,
    background: "#ffffff",
    iconRatio: flatIconRatio,
  },
  {
    fileName: "reviewflow_disc.png",
    treatment: "disc",
    size: 96,
    background: undefined,
    iconRatio: discIconRatio,
  },
  // Both app avatars — GitHub App and Slack app — are cropped to a square and
  // shown over light and dark chrome, so they take the disc rather than the
  // flat mark, at 512 because both render far above the old 96px.
  {
    fileName: "reviewflow_github.png",
    treatment: "disc",
    size: 512,
    background: undefined,
    iconRatio: discIconRatio,
  },
  // Editable masters, so a one-off size or a vector embed needs no re-run.
  {
    fileName: "reviewflow.svg",
    treatment: "flat",
    size: 512,
    background: undefined,
    iconRatio: flatIconRatio,
  },
  {
    fileName: "reviewflow_disc.svg",
    treatment: "disc",
    size: 512,
    background: undefined,
    iconRatio: discIconRatio,
  },
];

const colors = readBrandColors();
const icon = readIconSource(iconName);
console.log(
  `${iconName}, green ${colors.green} on ${colors.onGreen}, from the webapp brand palette`,
);

const browser = await chromium.launch();

try {
  for (const { fileName, ...svgParams } of logos) {
    const svg = buildSvg({ ...svgParams, icon, colors });
    const outputUrl = new URL(fileName, logosDir);

    if (fileName.endsWith(".svg")) {
      writeFileSync(outputUrl, `${svg}\n`);
    } else {
      const { size } = svgParams;
      const page = await browser.newPage({
        viewport: { width: size, height: size },
        deviceScaleFactor: 1,
      });
      await page.setContent(
        `<style>html,body{margin:0;padding:0}</style>${svg}`,
      );
      // The svg paints its own background when the spec asks for one, so the
      // page itself never contributes anything opaque.
      writeFileSync(outputUrl, await page.screenshot({ omitBackground: true }));
      await page.close();
    }

    console.log(`  ${fileName}`);
  }
} finally {
  await browser.close();
}
